### PR TITLE
Mate Weather Panel Fix

### PR DESCRIPTION
**Pull request by calexil**
Source of fix:

https://github.com/mate-desktop/libmateweather/commit/835055e0d0b950d3f66ad236de7e40942f6f7d8e

### CODE REVIEW

**Comment by calexil** [comment]
@clefebvre I guess this was closed because the fixed xenial package is being added.

**Comment by clefebvre** [comment]
It's just patched in Mint, and your fix is right but not in the right place :)

**Comment by clefebvre** [comment]
For 1.14 and 1.12 it's a new release (like you did). For older versions it's a patch.

**Comment by calexil** [comment]
cool.

**Pull request closed without merging**
